# Default values for hanami-project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

user:
  id: "test_user"
  name: "Test User"
  pw: "asdfasdf"

token:
  pw: "asdf"
  expire_time: 3600

docker:
  tag: "develop"
  registry: "kitsudaiki"

api:
  port: 1337
  ip: "0.0.0.0"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
