version: 2

updates:
  - package-ecosystem: pip
    directory: "/src/sdk/python/hanami_sdk/"
    schedule:
      interval: daily
      time: "12:00"
    labels:
      - "Code: python"
      - "Env: Dependencies"
    groups:
      python-packages:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    assignees:
      - "kitsudaiki"
    ignore:
      - dependency-name: 'protobuf'
        # Must be pinned to a maximum of version 3.20.3
        # see https://github.com/protocolbuffers/protobuf/issues/10051
        versions: '> 3.20.3'

  - package-ecosystem: gomod 
    directory: "/src/cli/hanamictl/"
    schedule:
      interval: daily
      time: "12:00"
    labels:
      - "Code: go"
      - "Env: Dependencies"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10
    rebase-strategy: "auto" 
    assignees:
      - "kitsudaiki"
