site_name: Hanami-AI-Documentation
theme:
  name: material
  language: en
  logo: img/hanami-logo-pink.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - navigation.top
    - content.code.annotate 
    - content.tabs.link

plugins:
    - search
    - drawio-exporter:
        # Diagrams are cached to speed up site generation. The default path is
        # drawio-exporter, relative to the documentation directory.
        cache_dir: 'drawio-exporter'
        # Path to the Draw.io executable:
        #   * drawio on Linux
        #   * draw.io on macOS
        #   * or draw.io.exe on Windows
        # We'll look for it on your system's PATH, then default installation
        # paths. If we can't find it we'll warn you.
        drawio_executable: null
        # Additional Draw.io CLI args
        drawio_args: []
        # Output format (see draw.io --help | grep format)
        format: svg
        # Embed format
        #   * The default is to embed via the <img> tag, only rewriting the
        #     value of the src attribute.
        #   * Consider <object type="image/svg+xml" data="{img_src}"></object>
        #     to enable interactive elements (like hyperlinks) in SVGs.
        embed_format: '{img_open}{img_src}{img_close}'
        # Glob pattern for matching source files
        sources: '*.drawio'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 

extra_css:
  - stylesheets/extra.css

copyright: all rights reserved; 2022-2023 Tobias Anker

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kitsudaiki
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tobias-anker
