# more than 1 replica is currently not supported
replicaCount: 1

user:
  id: "test_user"
  name: "Test User"
  pw: "asdfasdf"

token:
  pw: "asdf"
  expire_time: 3600

docker:
  tag: "develop"
  registry: "kitsudaiki"

api:
  domain: local-hanami

processing:
  # use per default 50% of the available memory for pre-allocation
  use_of_free_memory: 0.5

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
