# Default values for openhanami-project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

user:
  id: "test_user"
  name: "Test User"
  pw: "asdfasdf"

token:
  pw: "asdf"
  expire_time: 3600

docker:
  tag: "develop"
  registry: "kitsudaiki"

api:
  domain: local-hanami
  port: 11418
  ip: "0.0.0.0"

processing:
  use_of_free_memory: 0.5

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
