---
hanami_debug: true

hanami_docker_tag: "develop"
hanami_listen_address: "0.0.0.0"
hanami_log_dir: "/var/log/hanami"

hanami_dataset_location: "/etc/hanami/datasets"
hanami_checkpoint_location: "/etc/hanami/checkpoints"
hanami_tempfile_location: "/etc/hanami/tempfiles"

hanami_token_key_path: "/etc/hanami/token_key"
hanami_ssl_cert_path: "/etc/hanami/cert.pem"
hanami_ssl_key_path: "/etc/hanami/key.pem"
