apiVersion: v1
metadata:
  name: hanami-config
data:
  hanami.conf: |+
    [DEFAULT]
    debug = True
    log_path = "/var/log"
    database = "/etc/hanami/data/hanami_db"
    use_cuda = false

    [storage]
    dataset_location = "/etc/hanami/data/datasets"
    checkpoint_location = "/etc/hanami/data/checkpoints"
    tempfile_location = "/etc/hanami/data/tempfiles"
    tempfile_timeout = 10

    [auth]
    policies = "/etc/hanami/policies"
    token_key_path = "/etc/hanami/token_key"
    token_expire_time = {{ .Values.token.expire_time }}

    [http]
    enable = True
    ip = {{ .Values.api.ip }}
    port = {{ .Values.api.port }}

kind: ConfigMap
