apiVersion: v1
metadata:
  name: azuki-config
data:
  azuki.conf: |
    [DEFAULT]
    #debug = True
    log_path = "/var/log/azuki"
    sakura-file-locaion = "/etc/azuki/sakura-files"
    address = "/tmp/hanami/azuki.uds"
    database = "/etc/azuki/azuki_db"

    [torii]
    address = "/tmp/hanami/torii.uds"

    [misaki]
    address = "/tmp/hanami/misaki.uds"

    [shiori]
    address = "/tmp/hanami/shiori.uds"

    [kyouko]
    address = "/tmp/hanami/kyouko.uds"
kind: ConfigMap
