apiVersion: v1
metadata:
  name: hanami-config
data:
  hanami.conf: |+
    [DEFAULT]
    debug = True
    log_path = "/var/log"
    database = "/etc/hanami/hanami_db"
    socket_path = "/tmp/hanami"

    [storage]
    data_set_location = "/etc/hanami/train_data"
    checkpoint_location = "/etc/hanami/checkpoint"

    [auth]
    policies = "/etc/hanami/policies"
    token_key_path = "/etc/hanami/token_key"
    token_expire_time = {{ .Values.token.expire_time }}

    [http]
    enable = True
    ip = "0.0.0.0"
    certificate = "/etc/hanami/cert.pem"
    key = "/etc/hanami/key.pem"
    dashboard_files = "/etc/hanami/Hanami-AI-Dashboard/src"
    port = 1337
    enable_dashboard = True

    [azuki]
    enable = False

kind: ConfigMap
